### ISSUE TITLE
Unhandled Promise Rejection 

### ISSUE THREAD

**Issue by sclippwottier** [Lumerin-protocol/WalletDesktop#171]
Error occurred on a MacMini Server 2012 using  MacOS 10.14.6  and received this error multiple times while contracts were running on latest Lumerin Wallet 1.1.6 (I didn’t see this error on 1.14)

Unhandled Promise Rejection
Error: Invalid JSON RPC response: {"size":0,"timeout":0}
    at Object.InvalidResponse (/Applications/Lumerin Wallet.app/Contents/Resources/app.asar/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at /Applications/Lumerin Wallet.app/Contents/Resources/app.asar/node_modules/web3-providers-http/lib/index.js:129:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by abs2023** [comment]
Thanks for reporting this issue.  We have recognized that our API calls from the wallet to Sepolia needed to be optimized and leverage different back-end infrastructure.  An update is being tested and will be released in the next few days that will eliminate issues found in both version 1.1.4 and 1.1.6.  Thank you for your patience as we work through these issues.

**Comment by romblch** [comment]
Windows Server 2016  Lumerin Wallet 1.1.10

Unhandled Promise Rejection
Error: CONNECTION ERROR: Couldn't connect to node https://rpc.ankr.com/eth_sepolia.
    at Object.ConnectionError (C:/Users/Administrator/AppData/Local/Programs/lumerin-wallet-desktop/resources/app.asar/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.InvalidConnection (C:/Users/Administrator/AppData/Local/Programs/lumerin-wallet-desktop/resources/app.asar/node_modules/web3-core-helpers/lib/errors.js:36:21)
    at HttpProvider.failed (C:/Users/Administrator/AppData/Local/Programs/lumerin-wallet-desktop/resources/app.asar/node_modules/web3-providers-http/lib/index.js:139:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
